schema:
  - http://152.228.215.94:83/api:
      headers: {
        mode: 'no-cors'
      }
documents:
  - 'src/**/*.graphql'
generates:
  src/utils/__generated__/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withRefetchFn: true